### ISSUE TITLE
(on-premise) SP.UI.Controls.Navigation seems bugged.

### ISSUE THREAD

**Issue by thaxy** [OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials#1]
Hi,

I am currently testing your tutorial/guideline on my on-premise SP 2013 Enterpise Server (with CU January 2016).
It seems that my Ribbon/Chrome control is somehow bugged.
I tested it in different browsers from IE, Edge to FireFox.
![capture](https://cloud.githubusercontent.com/assets/1968007/12945757/d272c846-cfef-11e5-93d5-ab91704cbd06.PNG)
As you see in the image above the icon of the question mark is not displayed correctly. Furthermore I don't have a background change and right border when I hover/click the icon. That's a diffrent behaviour compared to the 'official' ribbon.
![untitled](https://cloud.githubusercontent.com/assets/1968007/12945886/c4a59ddc-cff0-11e5-98fb-fc9e345e4bfe.png)

Last but not least I can't close the dropdown window when I click on an empty page area.
I don't get any script errors...

Is this a bug or normal? Can anyone guide me in a direction for a fix. I can't debug that minified SP.UI.Controls.js. 

thaxy

**Comment by thaxy** [comment]
Ok, wow. Really weird. I downloaded the SharePoint Online version of the correspondening .js file.
https://cdn.sharepointonline.com/15761/_layouts/15/16.0.4921.1214/SP.UI.Controls.js
Included it in my provider-hosted project and it worked. So there are two possibiliites left:
a) My SharePoint installation is messed up that contains the old / bugged .js file
b) On-premise SharePoint is not well maintained and it hasn't been fixed because noone uses it

My colleagues are going to install a fresh (latest msdn) SP 2013 Foundation version for a customer tomorrow. I am going to grab this file too and report it here to tell us if point a) or b) is true.

**Comment by Rick-Kirkham** [comment]
This is a known bug in the Chrome Control. See [Chrome Help Icon Missing](https://social.msdn.microsoft.com/Forums/office/en-US/7ea43ea5-c162-4949-935f-dc3e1f249a08/chrome-help-icon-missing?forum=appsforsharepoint) for a fix. Since this is not really an issue with the samples in this repo, I'm closing this issue

**Comment by thaxy** [comment]
Thanks for your help and the great repo you provided here.
