### ISSUE TITLE
Not working for SP 2013 / Visual Studio 2015

### ISSUE THREAD

**Issue by datasmithtech** [OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials#2]
I downloaded to my server, 
Windows 2012 R2

"The required version of SharePoint Foundation or SharePoint Server is not installed on this system. The target version of the SharePoint project is 16.1.	ChainStore		0

**Comment by Rick-Kirkham** [comment]
The sample was created with SharePoint 16.0.0.0, so the app manifest was created with the SharePointMinVersion set to that version, but it will work on SharePoint 2013 too. Open the AppManifest.xml file and change the SharePointMinVersion value to "15.0.0.0". I'll clarify this in the readme. Thanks for pointing this out.

**Comment by coakleypa** [comment]
I am still seeing the warning "The required version of SharePoint Foundation or SharePoint Server is not installed on this system. The target version of the SharePoint project is 16.1." after I changed the AppManifest.xml to _SharePointMinVersion="15.0.0.0"_. I am using VS2015.

Is there any additional modifications required to run this on SharePoint 2013 on-premises ?

**Comment by Rick-Kirkham** [comment]
I cannot reproduce this. Are you seeing this in a production add-in or in one that you are running with F5 in Visual Studio. If you are loading the add-in in some other way, then it is probably the old version of the manifest that is being used.

**Comment by Ofer-Gal** [comment]
Where is the AppManifest.xml  file?

**Comment by Rick-Kirkham** [comment]
It is in the root of the ChainStore folder (not ChainStoreWeb or ChainStoreDB).
