### ISSUE TITLE
Error This project references NuGet package(s) that are missing on this computer

### ISSUE THREAD

**Issue by rahulayal17** [OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials#3]
I am getting below error while debugging solution 1_BeforeSharePointUI

Severity	Code	Description	Project	File	Line	Suppression State
Error		This project references NuGet package(s) that are missing on this computer. Use NuGet Package Restore to download them.  For more information, see http://go.microsoft.com/fwlink/?LinkID=322105. The missing file is ..\packages\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.1.0.0\build\Microsoft.CodeDom.Providers.DotNetCompilerPlatform.props.	ChainStoreWeb	C:\Users\Administrator\Desktop\SharePoint_Provider-hosted_Add-ins_Tutorials-master\SharePoint_Provider-hosted_Add-ins_Tutorials-master\1_BeforeSharePointUI\ChainStoreWeb\ChainStoreWeb.csproj	229	

can anyone help me with this.

**Comment by Rick-Kirkham** [comment]
This message means that you don't have Microsoft.CodeDom.Providers.DotNetCompilerPlatform installed on your developer machine. In Visual Studio, open the **TOOLS** menu open **NuGet Package Manager** and then **Manage NuGet Packages for Solution**. Then use the manager to install the missing package. See Visual Studio help for details.
