### ISSUE TITLE
connectionString does not function with latest SQL Server release (SQL Sever 2016)

### ISSUE THREAD

**Issue by jrhender** [OfficeDev/SharePoint_Provider-hosted_Add-ins_Tutorials#4]
With the release of SQL Server 2016, the SSDT db instance is "(localdb)\ProjectsV**13**". However, connectionString in the web.config file of the ChainStoreWeb project points towards "(localdb)\ProjectsV**12**".  Therefore if the latest SQL Server release is installed, an exception of type 'System.Data.SqlClient.SqlException' occurs when establishing a connection to SQL Server.

Therefore, in my opinion, so that this project functions 'out-of-the-box' using the current articles, the connectionStrings should be updated to V13

@Rick-Kirkham if you agree with this suggestion, I don't mind updating the queryString in each solution. I would like to save future users the bit of debugging that I did.

**Comment by Rick-Kirkham** [comment]
**@jrhender** Thanks for pointing this out. Since new versions of SQL Server are adopted slowly over a period of years, many developers will still be using V12, so I think the best strategy here is for me to add an instruction to the ReadMe that tells V13 users to edit the web.config files.
